# Generated by Django 5.1 on 2024-08-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_electric',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_new',
        ),
    ]
