# Generated by Django 5.1 on 2024-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_make_car_name_remove_car_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
